# Generated by Django 4.1.7 on 2023-06-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
